### PR TITLE
Fix for issue-142

### PR DESCRIPTION
**Pull request by abukres**

### CODE REVIEW

**Comment by abukres** [comment]
Fix for issue-142

**Comment by nvisionative** [comment]
@abukres please clean up the DLL references.  This commit contains references to the install location rather than the project relative **packages** folder.  Thanks!

**Comment by abukres** [comment]
nvQuickSite.csproj was not supposed to be in there. I will remove it. btw, the metroframework packages are not downloading any assemblies. Even tried it manually. Maybe something wrong with Nuget.

**Comment by nvisionative** [comment]
Thanks!  Yeah, NuGet is a real pain sometimes - glad you got it working (even though you had to go with direct references.  What We usually have to do (in a new dev environment) is Clean first, then Rebuild.  Rebuild theoretically should clean first, but something funky happens woth NuGet that way.  ;-(

**Pull request closed without merging**
