### PR TITLE
Change button text

### LINKED ISSUE #311: Change text Cancel to Close
I love the remove Existing Sites option. Shouldn't the button be named **Close** and not **Cancel**?

image

### PR DESCRIPTION
**Pull request by EPTamminga**
Resolves #311

### CODE REVIEW

**Review by valadas — APPROVED** [review]
While we are at it could we rename metroButton2 to btnClose or some such ? Other than that, I am good with this change either way.

**Comment by david-poindexter** [comment]
> While we are at it could we rename metroButton2 to btnClose or some such ? Other than that, I am good with this change either way.

@valadas I agree with the recommended change.  Let's go ahead and merge this PR and we can create a new PR for the control name change.

@EPTamminga I am also going to update your PR description so #311 will be auto-closed upon merging this PR.  Thanks for your contribution!  🎉

**Review by david-poindexter — APPROVED** [review]

**Comment by EPTamminga** [comment]
@david-poindexter: it was a massive change :-) 

(While I made the issue, my idea was to solve it in the same round)

**Comment by david-poindexter** [comment]
Thanks @EPTamminga - no worries.  A change to the control name would need to be built and tested locally anyway.  So it was just as easy to split it up and get the cosmetics rolled in via this PR.

**Pull request merged**
