### PR TITLE
Fix for issue 136

### PR DESCRIPTION
**Pull request by abukres**

### CODE REVIEW

**Comment by abukres** [comment]
Fix for issue 136

**Comment by abukres** [comment]
Fix for issue 136

**Comment by nvisionative** [comment]
@abukres thank you for the pull request.  At first glance, this looks good.  Please merge your changes with the latest version of the master repository.  It appears you were starting from a fork of an older version of the repo.  Thanks again!  This may actually be the answer to some other file/folder permissions issues posted as well.

**Comment by abukres** [comment]
I forked it yesterday and worked on it. It should be from master. Why do you think it's from an old version?

**Comment by nvisionative** [comment]
I know it is based on an old version because I see old code in there.  ;-)  Most likely you started from the state of the last release, but there have been several commits since the last release.  Just make sure you pull latest commits from our master branch.  You can probably just merge.

**Comment by abukres** [comment]
What is your last release? master branch? Because that's what I forked from. The last commit you have is from 1/18/2017 so I am not sure what you mean by recent commits.

**Comment by abukres** [comment]
The two using statements were added by me. They aren't part of your code. Most of the changes you see are formatting differences. Show me code that you are considering as old code that shouldn't be there.
Your master branch is at least one year old. There's nothing new since 1/18/2017.

**Comment by nvisionative** [comment]
@abukres I am not sure how else to explain this.  Your commit for this PR contains **many** changes that are not pertinent to the specific issue you are trying to fix.  The code needs clean-up in order for the PR to be reviewed, accepted and merged.  I mentioned the using statement for **nvQuickSiteValidator** as an example because it was in a previous version of nvQuickSite, but is no longer is used or required.  Why did you add it back in?  

The goal here is to accept and merge your PR, so you are going to have to clean things up.  We don't have the time right now to sort through the **135 additions** and **43 deletions** in your commit.  :)

**Pull request closed without merging**
