### PR TITLE
Fix for Issue 140

### LINKED ISSUE #100: AppPool
Hi David,

First of all congrats on the great App! Really a great service to DNN and the community!

Problem I had when I tried: I have chosen a new AppPool for a DNN 8.0.1 install and the appPool was setup as .NET 2.0 - Maybe because this is the default on IIS, but it should have been setup with .NET 4

That's it for now!

Cheers,
Aderson

### LINKED ISSUE #140: "Unrecognized attribute 'targetFramework'" error when visiting site
"Unrecognized attribute 'targetFramework'" error in web.config error when visiting site.
That's because the app created a v2.0 .Net framework version of an IIS App pool instead of v4.0.
Windows 7.

### PR DESCRIPTION
**Pull request by abukres**
Fixes #140
Fixes #100

### CODE REVIEW

**Comment by nvisionative** [comment]
@abukres this PR now contains a commit that is not related to this PR.  Can you please re-submit without the [Fix for Issue-136](https://github.com/nvisionative/nvQuickSite/pull/141/commits/3fbdfc7f308b827f4a1e77b075b6c3393852fe70)?

**Comment by abukres** [comment]
It shouldn't. I pushed another commit,

**Comment by nvisionative** [comment]
Looks great - thank you @abukres!  By the way, do you have a Twitter account?  We like to publicly thank contributors via social media for every pull request.  🥇

**Comment by abukres** [comment]
@abdu3000. I replied to you a few days ago to one of your thanks messages.

**Comment by nvisionative** [comment]
Thank you for validating your Twitter handle.  Since your name is not associated with the GitHub account or Twitter handle (from what we could tell anyway), we just weren't sure.  :)

**Pull request merged**
